### PR TITLE
Change the counting method of clients

### PR DESCRIPTION
**Pull request by sh2**
Here is a sample fix for #73.

### CODE REVIEW

**Comment by k-yle** [comment]
Hi, thanks for the PR! not sure what's wrong with the CI... Anyway will take a look at this tonight :)

**Comment by k-yle** [comment]
Hi, I've rebased your PR so that the CI runs. Do you know why `wsServer.clients.size` doesn't work for this purpose? And do you have a way of testing this?

**Comment by sh2** [comment]
wsServer.clients.size represents the number of clients connected to the server.

If one server serves multiple streams,
It is desirable to close stream A when the number of clients connecting to stream A reaches zero.

With wsServer.clients.size, as long as we have another client connecting to a different stream B,
The condition to close stream A cannot be met. (wsServer.clients.size >= 1)

I am making a program to switch and display multiple surveillance cameras of 10 or more.
This program works as expected when used by a single person, and there is always one ffmpeg process.
However, when used by more than one person, eventually more than 10 ffmpeg processes will continue to work.
This puts an excessive load on the CPU and memory.

The test requires the use of two browsers.
Currently it is not automated. Excuse me.

Browser 1
```
await loadPlayer({url:'ws: //' + location.host +'/api/stream/1', canvas: c});
```

Browser 2
```
const p = await loadPlayer({url:'ws: //' + location.host +'/api/stream/2', canvas: c});
await timeout(5000);
p.destroy();
```

It's a good idea to check if stream/2 closes this way.
Thanks,

**Comment by k-yle** [comment]
thanks @sh2, this fix has been released in `v1.4.1`

**Comment by sh2** [comment]
Thank you very much! 😃

**Pull request merged**
